# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    # Check for updates managed by npm once a week
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "friday"
      # Check for npm updates at 9pm
      time: "21:00"
      # Use Western Indonesia Time (UTC +07:00)
      timezone: "Asia/Jakarta"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
