const CONFIG = {
  KEY: 'YOUR_API_KEY',
  BASE_URL: 'API_URL',
  BASE_IMAGE_URL: 'API_IMAGE_URL',
  DEFAULT_LANGUAGE: 'en-us',
  CACHE_NAME: 'CACHE_NAME',
  DATABASE_NAME: 'DB_NAME',
  DATABASE_VERSION: 1,
  OBJECT_STORE_NAME: 'OBJ_STORE_NAME',
};

export default CONFIG;
